language: node_js
node_js:
- lts/*
script:
  - npm run lint
  - npm test
deploy:
  provider: npm
  email: yume-wikijp@live.jp
  on:
    tags: true
  api_key:
    secure: kTH71R8SG6Wzq4CawTv0QD4vtUF55auTXOSU6cWCA7rKTQbg/L17AQcc0y+jvOoqUmOxqfr8J8a1Rls0s2SW54lBdoVcUDKSz6b6wDijPxXwXxdtLLL4UGk3otfz8onHBh821ZUhjGnQtuMSUE3OS7iZhPK4u33kJi4Rv5smlZg6OBXaNuZNWvFUdyhC7HodQxEZbP9NCwh8/bKQ+TUmOuspku9efI+70A+If5ngaum+Du3Rqt+iPWcI/9dCT/3P6r8xQHlYCRJURYgcpv3zxtMcVkaNhdqHbzOIa4zLzPsU7Aqc4lLOa70jEqWOG3fSFXddwsk+L1652NNnhJaZ4PHIi2s97Ue/z3eUzi7HG7akshH2EnqClvGkY7tmBTcr5kfeSsWXfdJjU5gawH8RxfTFNct7Gc3Vb6ljNnyOvzl0QrPn3Lt2xwQjNUF8egqhDOErKesHw9rwBXyC0j4SigJZWgSFrMQ6ZKv+Ud7tDUeHhDWZwQQVxZn7Vng9ENIvZOoOK9qgZXlZmggpxp1RwTEjXQlmF01WbLzs9OBozZ0r0cN9/+jTw+/1GkepT1516XhlEh+ArDvh2R4dW3dtfHPTZm6wa6Y57qDq/h5FVgxcmk6FL3km+0ojlNK+ZhqsMq/Yzp0z4eWGOENrKYPyTMr1mBBZopkdqpGaud+AawY=
