language: node_js
node_js:
- lts/*
cache: npm
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: yume-wikijp@live.jp
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: R88Mx1U2YF2dLq+SNGjY2LZHrKYCNijs0t1Iwh4KjMG8JQMew/Ph4JljyeAlri5vz7JDtWjB7Nm9tIRYriT9MjG0wcd69hpRSExHyW0nfwCG9Ik9uqUvrQ6Kp8Cnns0nmcE1mPXrqWVH3bpzI/qwJGA6n30TlxzxF10xN9jYgfiZMx9OZGj5UA99GM67BRQxvyPUA9kjaCco4yU16HZ3twNZUHE14wPOwrvzRd77Afl/1UYDEMd8EkyucIaNAT+fdcjVWH/JK4iFKaH25d7OKPFgvYWv+9Xs6mvJjWK3x15FTbBr5rmmpDimzFXOligf61/Q5BOa+6xjAF5Pzz9vIH5lqh4SjSv+oXJ8NzgdoD9NsL7faiJDPA9wYbILnayeY1I598QWIPBy9f+GnR21udGxECjs9X+0BxWoNMCmx9XYw4wmYtJEhwFmmESDaomkp+XSPZDE6zBIfzIl72gIzg3fTSJyjmAgQ8T+gmIjYU1VZUW+9tI8wRhq7dISnY2/TtDaLqmdJU2+UUCqpiYGNRybMjCavCOF+u6LCxao20XxntKPhF49ZY3DVi3W5YE9+b0k7yCIfTxlfxP/5Fy/dUq9hBWLmyXDHnjIhsEUjYqnmYXabmuTiCqx6cFV60eBMkYrsOF3dluYOh3POvkVkFkXjLmCObfste+CD2/G28o=
